package entidades;
// Generated 28-11-2017 17:43:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String rut;
     private String nombre;
     private Set pedidos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String rut, String nombre) {
        this.rut = rut;
        this.nombre = nombre;
    }
    public Cliente(String rut, String nombre, Set pedidos) {
       this.rut = rut;
       this.nombre = nombre;
       this.pedidos = pedidos;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


