package entidades;
// Generated 28-11-2017 17:43:30 by Hibernate Tools 4.3.1



/**
 * Detallepedido generated by hbm2java
 */
public class Detallepedido  implements java.io.Serializable {


     private Integer iddetalle;
     private Pedido pedido;
     private Producto producto;
     private int total;

    public Detallepedido() {
    }

    public Detallepedido(Pedido pedido, Producto producto, int total) {
       this.pedido = pedido;
       this.producto = producto;
       this.total = total;
    }

    public Detallepedido(Integer iddetalle) {
        this.iddetalle = iddetalle;
    }
   
    public Integer getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(Integer iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }




}


