package entidades;
// Generated 28-11-2017 17:43:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer ticket;
     private Cliente cliente;
     private String formapago;
     private boolean agranda;
     private boolean llevar;
     private int cantidad;
     private Set detallepedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, String formapago, boolean agranda, boolean llevar, int cantidad) {
        this.cliente = cliente;
        this.formapago = formapago;
        this.agranda = agranda;
        this.llevar = llevar;
        this.cantidad = cantidad;
    }
    public Pedido(Cliente cliente, String formapago, boolean agranda, boolean llevar, int cantidad, Set detallepedidos) {
       this.cliente = cliente;
       this.formapago = formapago;
       this.agranda = agranda;
       this.llevar = llevar;
       this.cantidad = cantidad;
       this.detallepedidos = detallepedidos;
    }
   
    public Integer getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Integer ticket) {
        this.ticket = ticket;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(String formapago) {
        this.formapago = formapago;
    }
    public boolean isAgranda() {
        return this.agranda;
    }
    
    public void setAgranda(boolean agranda) {
        this.agranda = agranda;
    }
    public boolean isLlevar() {
        return this.llevar;
    }
    
    public void setLlevar(boolean llevar) {
        this.llevar = llevar;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


