package entidades;
// Generated 28-11-2017 17:43:30 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

    private Integer idproducto;
    private String descripcion;
    private int valor;
    private int cantidad;
    private Set detallepedidos = new HashSet(0);

    public Producto() {
    }

    public Producto(Integer idproducto) {
        this.idproducto = idproducto;
    }

    public Producto(String descripcion, int valor, int cantidad) {
        this.descripcion = descripcion;
        this.valor = valor;
        this.cantidad = cantidad;
    }

    public Producto(String descripcion, int valor, int cantidad, Set detallepedidos) {
        this.descripcion = descripcion;
        this.valor = valor;
        this.cantidad = cantidad;
        this.detallepedidos = detallepedidos;
    }

    public Integer getIdproducto() {
        return this.idproducto;
    }

    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getValor() {
        return this.valor;
    }

    public void setValor(int valor) {
        this.valor = valor;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public Set getDetallepedidos() {
        return this.detallepedidos;
    }

    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }

}
